"""initial schema

Revision ID: a7367f120317
Revises:
Create Date: 2026-07-22 23:27:05.530596
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a7367f120317"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.create_table(
        "businesses",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
        sa.UniqueConstraint("slug", name=op.f("uq_businesses_slug")),
    )
    op.create_table(
        "telegram_users",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_users")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_telegram_users_telegram_user_id")),
    )
    op.create_table(
        "audit_log",
        sa.Column("business_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_audit_log_actor_user_id_telegram_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_audit_log_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        op.f("ix_audit_log_actor_user_id"), "audit_log", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_business_id"), "audit_log", ["business_id"], unique=False)
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_table(
        "bot_installations",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_bot_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("token_ciphertext", sa.Text(), nullable=False),
        sa.Column("webhook_path_secret", sa.String(length=64), nullable=False),
        sa.Column("webhook_header_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_bot_installations_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_installations")),
        sa.UniqueConstraint("telegram_bot_id", name=op.f("uq_bot_installations_telegram_bot_id")),
        sa.UniqueConstraint(
            "webhook_path_secret", name=op.f("uq_bot_installations_webhook_path_secret")
        ),
    )
    op.create_index(
        op.f("ix_bot_installations_business_id"), "bot_installations", ["business_id"], unique=False
    )
    op.create_table(
        "business_members",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_business_members_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegram_users.id"],
            name=op.f("fk_business_members_user_id_telegram_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_members")),
        sa.UniqueConstraint("business_id", "user_id", name=op.f("uq_business_members_business_id")),
    )
    op.create_index(
        op.f("ix_business_members_business_id"), "business_members", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_business_members_user_id"), "business_members", ["user_id"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_locations_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
    )
    op.create_index(op.f("ix_locations_business_id"), "locations", ["business_id"], unique=False)
    op.create_table(
        "masters",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_masters_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegram_users.id"],
            name=op.f("fk_masters_user_id_telegram_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_masters")),
    )
    op.create_index(op.f("ix_masters_business_id"), "masters", ["business_id"], unique=False)
    op.create_index(op.f("ix_masters_user_id"), "masters", ["user_id"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_notification_preferences_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegram_users.id"],
            name=op.f("fk_notification_preferences_user_id_telegram_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint(
            "business_id", "user_id", name=op.f("uq_notification_preferences_business_id")
        ),
    )
    op.create_index(
        op.f("ix_notification_preferences_business_id"),
        "notification_preferences",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "services",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("buffer_before_minutes", sa.Integer(), nullable=False),
        sa.Column("buffer_after_minutes", sa.Integer(), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("requires_deposit", sa.Boolean(), nullable=False),
        sa.Column("deposit_minor", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "buffer_after_minutes >= 0", name=op.f("ck_services_buffer_after_nonnegative")
        ),
        sa.CheckConstraint(
            "buffer_before_minutes >= 0", name=op.f("ck_services_buffer_before_nonnegative")
        ),
        sa.CheckConstraint("duration_minutes > 0", name=op.f("ck_services_duration_positive")),
        sa.CheckConstraint(
            "price_minor IS NULL OR price_minor >= 0", name=op.f("ck_services_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_services_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_index(op.f("ix_services_business_id"), "services", ["business_id"], unique=False)
    op.create_table(
        "calendar_entries",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("master_id"), "="),
            (sa.text("tstzrange(starts_at, ends_at, '[)')"), "&&"),
            where=sa.text("state = 'active'"),
            using="gist",
            name="ex_calendar_entries_no_active_overlap",
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_calendar_entries_calendar_interval_positive")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_calendar_entries_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_calendar_entries_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["masters.id"],
            name=op.f("fk_calendar_entries_master_id_masters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_entries")),
    )
    op.create_index(
        op.f("ix_calendar_entries_business_id"), "calendar_entries", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_entries_location_id"), "calendar_entries", ["location_id"], unique=False
    )
    op.create_index(
        "ix_calendar_entries_master_starts_at",
        "calendar_entries",
        ["master_id", "starts_at"],
        unique=False,
    )
    op.create_table(
        "master_services",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("duration_override_minutes", sa.Integer(), nullable=True),
        sa.Column("price_override_minor", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_override_minutes IS NULL OR duration_override_minutes > 0",
            name=op.f("ck_master_services_duration_override_positive"),
        ),
        sa.CheckConstraint(
            "price_override_minor IS NULL OR price_override_minor >= 0",
            name=op.f("ck_master_services_price_override_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_master_services_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["masters.id"],
            name=op.f("fk_master_services_master_id_masters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_master_services_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_master_services")),
        sa.UniqueConstraint("master_id", "service_id", name=op.f("uq_master_services_master_id")),
    )
    op.create_index(
        op.f("ix_master_services_business_id"), "master_services", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_master_services_master_id"), "master_services", ["master_id"], unique=False
    )
    op.create_index(
        op.f("ix_master_services_service_id"), "master_services", ["service_id"], unique=False
    )
    op.create_table(
        "schedule_exceptions",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("exception_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "start_time IS NULL OR end_time IS NULL OR end_time > start_time",
            name=op.f("ck_schedule_exceptions_exception_interval_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_schedule_exceptions_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_schedule_exceptions_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["masters.id"],
            name=op.f("fk_schedule_exceptions_master_id_masters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_exceptions")),
    )
    op.create_index(
        op.f("ix_schedule_exceptions_business_id"),
        "schedule_exceptions",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_exceptions_exception_date"),
        "schedule_exceptions",
        ["exception_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_exceptions_location_id"),
        "schedule_exceptions",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_exceptions_master_id"), "schedule_exceptions", ["master_id"], unique=False
    )
    op.create_table(
        "working_rules",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_time > start_time", name=op.f("ck_working_rules_working_interval_positive")
        ),
        sa.CheckConstraint(
            "weekday >= 0 AND weekday <= 6", name=op.f("ck_working_rules_weekday_range")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_working_rules_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_working_rules_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["masters.id"],
            name=op.f("fk_working_rules_master_id_masters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_working_rules")),
    )
    op.create_index(
        op.f("ix_working_rules_business_id"), "working_rules", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_working_rules_location_id"), "working_rules", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_working_rules_master_id"), "working_rules", ["master_id"], unique=False
    )
    op.create_table(
        "appointments",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_entry_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("service_name_snapshot", sa.String(length=160), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("client_name_snapshot", sa.String(length=160), nullable=True),
        sa.Column("client_phone_snapshot", sa.String(length=32), nullable=True),
        sa.Column("client_comment", sa.Text(), nullable=True),
        sa.Column("internal_note", sa.Text(), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_minutes > 0", name=op.f("ck_appointments_appointment_duration_positive")
        ),
        sa.CheckConstraint(
            "price_minor IS NULL OR price_minor >= 0",
            name=op.f("ck_appointments_appointment_price_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_appointments_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["calendar_entry_id"],
            ["calendar_entries.id"],
            name=op.f("fk_appointments_calendar_entry_id_calendar_entries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["telegram_users.id"],
            name=op.f("fk_appointments_client_id_telegram_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_appointments_created_by_user_id_telegram_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_appointments_service_id_services"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
        sa.UniqueConstraint("calendar_entry_id", name=op.f("uq_appointments_calendar_entry_id")),
    )
    op.create_index(
        op.f("ix_appointments_business_id"), "appointments", ["business_id"], unique=False
    )
    op.create_index(op.f("ix_appointments_client_id"), "appointments", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_appointments_created_by_user_id"),
        "appointments",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_service_id"), "appointments", ["service_id"], unique=False
    )
    op.create_index(op.f("ix_appointments_status"), "appointments", ["status"], unique=False)
    op.create_table(
        "slot_holds",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_entry_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_slot_holds_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["calendar_entry_id"],
            ["calendar_entries.id"],
            name=op.f("fk_slot_holds_calendar_entry_id_calendar_entries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["telegram_users.id"],
            name=op.f("fk_slot_holds_client_id_telegram_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_slot_holds_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slot_holds")),
        sa.UniqueConstraint("calendar_entry_id", name=op.f("uq_slot_holds_calendar_entry_id")),
    )
    op.create_index(op.f("ix_slot_holds_business_id"), "slot_holds", ["business_id"], unique=False)
    op.create_index(op.f("ix_slot_holds_client_id"), "slot_holds", ["client_id"], unique=False)
    op.create_index(op.f("ix_slot_holds_expires_at"), "slot_holds", ["expires_at"], unique=False)
    op.create_index(op.f("ix_slot_holds_service_id"), "slot_holds", ["service_id"], unique=False)
    op.create_table(
        "time_blocks",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_entry_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_time_blocks_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["calendar_entry_id"],
            ["calendar_entries.id"],
            name=op.f("fk_time_blocks_calendar_entry_id_calendar_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_blocks")),
        sa.UniqueConstraint("calendar_entry_id", name=op.f("uq_time_blocks_calendar_entry_id")),
    )
    op.create_index(
        op.f("ix_time_blocks_business_id"), "time_blocks", ["business_id"], unique=False
    )
    op.create_table(
        "appointment_history",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("appointment_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=True),
        sa.Column("event_payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_appointment_history_actor_user_id_telegram_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_appointment_history_appointment_id_appointments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_appointment_history_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointment_history")),
    )
    op.create_index(
        op.f("ix_appointment_history_actor_user_id"),
        "appointment_history",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointment_history_appointment_id"),
        "appointment_history",
        ["appointment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointment_history_business_id"),
        "appointment_history",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "notification_jobs",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("appointment_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_notification_jobs_appointment_id_appointments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_notification_jobs_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["telegram_users.id"],
            name=op.f("fk_notification_jobs_recipient_user_id_telegram_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_jobs")),
        sa.UniqueConstraint(
            "appointment_id",
            "recipient_user_id",
            "kind",
            "scheduled_for",
            name=op.f("uq_notification_jobs_appointment_id"),
        ),
    )
    op.create_index(
        op.f("ix_notification_jobs_appointment_id"),
        "notification_jobs",
        ["appointment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_jobs_business_id"), "notification_jobs", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_jobs_recipient_user_id"),
        "notification_jobs",
        ["recipient_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_jobs_scheduled_for"),
        "notification_jobs",
        ["scheduled_for"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_jobs_state"), "notification_jobs", ["state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_jobs_state"), table_name="notification_jobs")
    op.drop_index(op.f("ix_notification_jobs_scheduled_for"), table_name="notification_jobs")
    op.drop_index(op.f("ix_notification_jobs_recipient_user_id"), table_name="notification_jobs")
    op.drop_index(op.f("ix_notification_jobs_business_id"), table_name="notification_jobs")
    op.drop_index(op.f("ix_notification_jobs_appointment_id"), table_name="notification_jobs")
    op.drop_table("notification_jobs")
    op.drop_index(op.f("ix_appointment_history_business_id"), table_name="appointment_history")
    op.drop_index(op.f("ix_appointment_history_appointment_id"), table_name="appointment_history")
    op.drop_index(op.f("ix_appointment_history_actor_user_id"), table_name="appointment_history")
    op.drop_table("appointment_history")
    op.drop_index(op.f("ix_time_blocks_business_id"), table_name="time_blocks")
    op.drop_table("time_blocks")
    op.drop_index(op.f("ix_slot_holds_service_id"), table_name="slot_holds")
    op.drop_index(op.f("ix_slot_holds_expires_at"), table_name="slot_holds")
    op.drop_index(op.f("ix_slot_holds_client_id"), table_name="slot_holds")
    op.drop_index(op.f("ix_slot_holds_business_id"), table_name="slot_holds")
    op.drop_table("slot_holds")
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_service_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_created_by_user_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_client_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_business_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_working_rules_master_id"), table_name="working_rules")
    op.drop_index(op.f("ix_working_rules_location_id"), table_name="working_rules")
    op.drop_index(op.f("ix_working_rules_business_id"), table_name="working_rules")
    op.drop_table("working_rules")
    op.drop_index(op.f("ix_schedule_exceptions_master_id"), table_name="schedule_exceptions")
    op.drop_index(op.f("ix_schedule_exceptions_location_id"), table_name="schedule_exceptions")
    op.drop_index(op.f("ix_schedule_exceptions_exception_date"), table_name="schedule_exceptions")
    op.drop_index(op.f("ix_schedule_exceptions_business_id"), table_name="schedule_exceptions")
    op.drop_table("schedule_exceptions")
    op.drop_index(op.f("ix_master_services_service_id"), table_name="master_services")
    op.drop_index(op.f("ix_master_services_master_id"), table_name="master_services")
    op.drop_index(op.f("ix_master_services_business_id"), table_name="master_services")
    op.drop_table("master_services")
    op.drop_index("ix_calendar_entries_master_starts_at", table_name="calendar_entries")
    op.drop_index(op.f("ix_calendar_entries_location_id"), table_name="calendar_entries")
    op.drop_index(op.f("ix_calendar_entries_business_id"), table_name="calendar_entries")
    op.drop_table("calendar_entries")
    op.drop_index(op.f("ix_services_business_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"), table_name="notification_preferences"
    )
    op.drop_index(
        op.f("ix_notification_preferences_business_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_masters_user_id"), table_name="masters")
    op.drop_index(op.f("ix_masters_business_id"), table_name="masters")
    op.drop_table("masters")
    op.drop_index(op.f("ix_locations_business_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_business_members_user_id"), table_name="business_members")
    op.drop_index(op.f("ix_business_members_business_id"), table_name="business_members")
    op.drop_table("business_members")
    op.drop_index(op.f("ix_bot_installations_business_id"), table_name="bot_installations")
    op.drop_table("bot_installations")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_business_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_user_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("telegram_users")
    op.drop_table("businesses")
    # ### end Alembic commands ###
